pipeline:
  name: InfraCodePipelineDeploy
  identifier: InfraCodePipelineDeploy
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: InfratetsingCodepipe
        build: <+input>
  stages:
    - stage:
        name: Clone
        identifier: Clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: CompressFile
                  identifier: CompressFile
                  spec:
                    shell: Sh
                    command: zip -r core.zip Core/
              - step:
                  type: Run
                  name: UploadArtifacttS3
                  identifier: UploadArtifacttoS3
                  spec:
                    shell: Sh
                    command: |-
                      aws configure set aws_access_key_id <+pipeline.variables.Accesskey>
                      aws configure set aws_secret_access_key <+pipeline.variables.Secretkey>
                      aws s3 cp core.zip s3://infratests3bucket123/core.zip
                      aws s3 cp InfraCodepipeline.yml s3://infratests3bucket123/
    - stage:
        name: deployStack
        identifier: deployStack
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: CreateCodePipeline
                    configuration:
                      stackName: DeployCodepipelinetesting
                      connectorRef: Aws
                      region: us-east-2
                      templateFile:
                        type: S3URL
                        spec:
                          templateUrl: https://infratests3bucket123.s3.us-east-2.amazonaws.com/InfraCodepipeline.yml
                      roleArn: ""
                  timeout: 10m
        tags: {}
  variables:
    - name: Accesskey
      type: Secret
      description: ""
      required: false
      value: Accesskey
    - name: Secretkey
      type: Secret
      description: ""
      required: false
      value: Secretkey
