pipeline:
  name: InfraCodePipelineDeploy
  identifier: InfraCodePipelineDeploy
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: InfratetsingCodepipe
        build: <+input>
  stages:
    - stage:
        name: Clone
        identifier: Clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: CompressFile
                  identifier: CompressFile
                  spec:
                    shell: Sh
                    command: "zip -r Core/Lambda.zip Core/Lambda.yaml \r\n"
              - step:
                  type: Run
                  name: UploadArtifacttS3
                  identifier: UploadArtifacttoS3
                  spec:
                    shell: Sh
                    command: "aws configure set aws_access_key_id <+pipeline.variables.Accesskey>\r\naws configure set aws_secret_access_key <+pipeline.variables.Secretkey>\r\naws s3 cp Core s3://infratests3bucket123/\r\n#aws s3 cp InfraCodepipeline.yml s3://infratests3bucket123/"
  variables:
    - name: Accesskey
      type: Secret
      description: ""
      required: false
      value: Accesskey
    - name: Secretkey
      type: Secret
      description: ""
      required: false
      value: Secretkey
