pipeline:
  name: InfraCodePipelineDeploy
  identifier: InfraCodePipelineDeploy
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: InfratetsingCodepipe
        build: <+input>
  stages:
    - stage:
        name: Clone
        identifier: Clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: CompressFile
                  identifier: CompressFile
                  spec:
                    shell: Sh
                    command: zip -r core.zip Core/
              - step:
                  type: Run
                  name: UploadArtifacttS3
                  identifier: UploadArtifacttoS3
                  spec:
                    shell: Sh
                    command: |-
                      aws configure set aws_access_key_id <+pipeline.variables.Accesskey>
                      aws configure set aws_secret_access_key <+pipeline.variables.Secretkey>
                      aws s3 cp core.zip s3://infratests3bucket123/core.zip
                      aws s3 cp InfraCodepipeline.yml s3://infratests3bucket123/
              - step:
                  type: Run
                  name: DepoyCodePipelinne
                  identifier: CreateStack
                  spec:
                    shell: Sh
                    command: |
                      aws configure set aws_access_key_id <+pipeline.variables.Accesskey>
                      aws configure set aws_secret_access_key <+pipeline.variables.Secretkey>
                      aws configure set region us-east-2
                      aws s3 cp s3://infratests3bucket123/InfraCodepipeline.yml .
                      aws cloudformation deploy --template-file InfraCodepipeline.yml --stack-name InfraCodepipelineDeploy 
                      aws codepipeline start-pipeline-execution --name DepolyInfraCodepipeline12
  variables:
    - name: Accesskey
      type: Secret
      description: ""
      required: false
      value: Accesskey
    - name: Secretkey
      type: Secret
      description: ""
      required: false
      value: Secretkey
